language: groovy
jdk:
  - openjdk7
  - oraclejdk8

env:
  global:
  - GIT_NAME="Iván López"
  - GIT_EMAIL="lopez.ivan@gmail.com"
  - secure: qdvGtJFbtvTJPZ9HbBC4DtPGLAeWQq5A1gX7u4xxfPBNw/Mkd7Z0/OrWiMuNMccDvqhiPAbauZRb3ZSE/KOWhqSKg6EAMeQpBgGUOrjXNBH6x0m2BthFkQhEVWrDVqGx+AuEbm7kRsNw6ec+kJ6oaBPjnHOfbPnGVro+4sGWSck=
  - secure: ZYo6fjlQNV1Oyc+fcINeISvR3pUAQG/V9I28v0xs2hjDiAug4gPnaQgxhmpa1SfRo5vwk+Oi+eNG22K2ePmUqARz2K5REahEPvocRZwrEow7pvJGvsLwiDcJk/o20fLPcUJlxgAyJeOQYR+exg35TlfHQ0ZWPVj07HO/A+1KTeM=

addons:
  postgresql: "9.4"

sudo: false

before_script:
  - psql -d template1 -c 'create extension hstore;' -U postgres
  - psql -c 'create database pg_extensions_test;' -U postgres
  - psql -c "create user postgres_extensions with password 'postgres_extensions';" -U postgres
  - psql -c "grant all privileges on database pg_extensions_test to postgres_extensions;" -U postgres
  - rm -rf target

script:
  - ./travis-build.sh

notifications:
  email:
    recipients:
      - lopez.ivan@gmail.com
      - alonso.javier.torres@gmail.com

    on_success: change
    on_failure: change

#after_success:
#  - ./gradlew cobertura coveralls
